### ISSUE TITLE
Could not load the PKCS#11 library/module: LoadLibraryA failed: 0x0000007E

### ISSUE THREAD

**Issue by stephenbriley** [disig/SoftHSM2-for-Windows#11]
Hi, 
I've installed SoftHSM 2.5.0 on a windows 2016 server.  The installation completes with no errors but when I attempt to run the following command:
C:\SoftHSM2\bin>softhsm2-util.exe --init-token --slot 0 --label "My token 1"

The following error appears:
ERROR: Could not load the PKCS#11 library/module: LoadLibraryA failed: 0x0000007E
ERROR: Please check log files for additional information.

I have the softhsm2.conf located in the C:\SoftHSM2\bin directory.  It has the following data in the config file.

directories.tokendir = .\tokens
objectstore.backend = file
log.level = INFO
slots.removable = false

Any ideas on what i'm doing wrong?
Thanks,
Steve

**Comment by jariq** [comment]
This is what MSI installer does:
- Creates configuration file `c:\SoftHSM2\etc\softhsm2.conf ` and sets environment variable `SOFTHSM2_CONF` to point to this file
- Installs PKCS#11 library `c:\SoftHSM2\lib\softhsm2.dll` and modifies `PATH` environment variable so it includes directory `c:\SoftHSM2\lib\` where this library is located

This is what `softhsm2-util.exe` does:
1. Resolves path to configuration file using `SOFTHSM2_CONF` environment variable 
2. Loads PKCS#11 library `softhsm2.dll` without specifying its full path so the linker resolves its location using the values from `PATH` environment variable

The error you are getting - `LoadLibraryA failed: 0x0000007E` - indicates that `softhsm2-util.exe` cannot load/locate `softhsm2.dll` so I guess that modification of `PATH` environment variable performed by MSI installer is not reflected in your session yet. Try logging out of Windows and logging back in.

**Comment by jariq** [comment]
@stephenbriley any news on this?

**Comment by Manucci85** [comment]
Hi @jariq 

I installed the portable version on win10 and I succeed to show my slots

`directories.tokendir = ..\var\softhsm2\tokens\
objectstore.backend = file
log.level = INFO
slots.removable = false`

`SOFTHSM2_CONF == c:\dev\softhsm\etc\softhsm2.conf`

(grosso merdo)
> path == %path% + c:\dev\softhsm\lib + %SOFTHSM2_CONF%

result:

> C:\dev\softhsm\bin>softhsm2-util.exe --show-slots
Available slots:
Slot 0
    Slot info:
        Description:      SoftHSM slot ID 0x0
        Manufacturer ID:  SoftHSM project
        Hardware version: 2.5
        Firmware version: 2.5
        Token present:    yes
    Token info:
        Manufacturer ID:  SoftHSM project
        Model:            SoftHSM v2
        Hardware version: 2.5
        Firmware version: 2.5
        Serial number:
        Initialized:      no
        User PIN init.:   no
        Label:

**Comment by edan81** [comment]
in my issue, I solve it by installing microsoft visual c++ 2015 redistributable 2019 x64.
