### ISSUE TITLE
SoftHSMv 2.6 just released

### ISSUE THREAD

**Issue by xnop** [disig/SoftHSM2-for-Windows#12]
Hi, thanks for building Windows version of SoftHSM2. Any plan to support the latest release, version 2.6, which has been released few days ago?

**Comment by jariq** [comment]
Sure I'll take a look at it.

I've seen 2.6.0rc1 announcement but I missed 2.6.0 announcement again. No matter how many channels I monitor they always announce it somewhere else 🤦‍♂ 

Signed source code release:
https://dist.opendnssec.org/source/softhsm-2.6.0.tar.gz
https://dist.opendnssec.org/source/softhsm-2.6.0.tar.gz.sig

**Comment by jariq** [comment]
Sadly SoftHSM 2.6.x currently cannot be built on Windows easily. See https://github.com/opendnssec/SoftHSMv2/issues/547 for more details.

**Comment by grisno** [comment]
Additional files to built SoftHSM v2.6.x on Windows
https://github.com/disig/SoftHSM2-for-Windows/pull/14
