### ISSUE TITLE
SoftHSM 2.2.0 Update

### ISSUE THREAD

**Issue by mengelhardt** [disig/SoftHSM2-for-Windows#2]
Can you perform a release for SoftHSM 2.2.0?

Thank you,
Mike

**Comment by jariq** [comment]
Sure. Looks like I've missed the [release announcement](https://www.opendnssec.org/2016/12/softhsm-2-2-0/).

**Comment by jariq** [comment]
[SoftHSM 2.2.0](https://github.com/disig/SoftHSM2-for-Windows/releases/tag/v2.2.0)
