### ISSUE TITLE
Is it possible to check for the dependencies in the installer?

### ISSUE THREAD

**Issue by sbke** [disig/SoftHSM2-for-Windows#4]
Hi, I tried using your project and had some trouble using it. I wasn't sure if I had the Visual C++ Redistributable depencies that are required but thought if it installed then they are probably there. The programm crashed on start and it took me a while to figure out that these dependencies where the issue. Is it possible to check for them during the install process? This might help other users as well.
Thank you.

**Comment by jariq** [comment]
That's a very interesting idea. I'll try to explore it before the next release.

**Comment by jariq** [comment]
We are using static linking since SoftHSM 2.4.0 so Visual C++ Redistributable no longer needs to be installed.
