### ISSUE TITLE
Generate ZMK using Clear components

### ISSUE THREAD

**Issue by dnyati** [disig/SoftHSM2-for-Windows#5]
I need to "Generate ZMK using Clear components". Could you please let me know how to generate ZMK using clear components using software. Is HSM (hardware ) mandatory for this or it is possible using software as well? If yes how? Can I use this production for 5000 transactions a day?

**Comment by jariq** [comment]
Hello, this repository hosts only binary builds and MSI installers of SoftHSM2 for MS Windows platform. Your question is too general and does not directly concern Windows build so please reopen issue in [SoftHSMv2](https://github.com/opendnssec/SoftHSMv2) repository.
